trigger:
- master
pr: none
pool:
  vmImage: ubuntu-latest

variables:
- group: my-variable-group

stages:
  - stage: TF_Install_Validate_PLAN_APPLY
    jobs:
      - job: TF_Install_Validate
        steps:
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Subscription'
            backendAzureRmResourceGroupName: 'ResourceGroup'
            backendAzureRmStorageAccountName: 'StorageAccount'
            backendAzureRmContainerName: 'Containername'
            backendAzureRmKey: 'terrafrom.tfstate'
        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            allowTelemetryCollection: true
      - job: TF_PLAN_APPLY
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Subscription'
            backendAzureRmResourceGroupName: 'ResourceGroup'
            backendAzureRmStorageAccountName: 'StorageAccount'
            backendAzureRmContainerName: 'Containername'
            backendAzureRmKey: 'terrafrom.tfstate'
        - task: TerraformCLI@0
          inputs:
            command: 'plan'
            allowTelemetryCollection: true
        - task: TerraformCLI@0
          inputs:
            command: 'apply'
            allowTelemetryCollection: true