apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql 
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-mediawiki
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pv-claim
        persistentVolumeClaim:
         claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: mysql
        volumeMounts:
        - name: mysql-pv-claim
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: root
          - name: MYSQL_USER
            valueFrom:
               secretKeyRef:
                  name: dbsecret
                  key: username
          - name: MYSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
          - name: MYSQL_DB
            valueFrom:
                configMapKeyRef:
                  name: dbconfig
                  key: database        
        ports:
        - containerPort: 3306