#echo -n 'USERNAME_STRING' | base64 => place the encrypted value in the username
#echo -n 'PASSWORD_STRING' | base64 => place the encrypted value in the password
#echo -n 'ROOT_PASSWORD_STRING' | base64 => place the encrypted value in the root
#echo -n 'WIKIADMIN_PUSERNAME_STRING' | base64 => place the encrypted value in the wikiadmin
#echo -n 'WIKIADMIN_PASSWORD_STRING' | base64 => place the encrypted value in the wikiadminpass

apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  username: cm9vdA==
  password: UGFzc3dvcmRAMTIz
  root: UGFzc3dvcmRAMTIz
  wikiadmin: cm9vdA==
  wikiadminpass: UGFzc3dvcmRAMTIz